projects:
  app:
    schemaPath: src/graphql/schema.graphql
    extensions:
      endpoints:
        user: http://localhost:4700
  db:
    schemaPath: src/generated/generated-schema/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      endpoints:
        default: 'http://localhost:4466/sufa'
